;
; OAM-NetworkService – PlatformIO custom configuration
; Targets: ESP32 REG1-LAN-TP-Base (IPCamera + SIP)
;

[custom]
build_flags =
  -D SERIAL_DEBUG=Serial
  -I lib/OGM-HardwareConfig/include/
  -fexceptions
  -D OPENKNX_LEDFUNC_BASE_PROG_UNCONFIGUREDSUPPORT


[custom_ESP32]
extends = ESP32, custom
build_flags =
  ${BASE.build_flags}
  -D OPENKNX_DUALCORE
  -D USE_ESP_ASNC_WEB_SERVER
  -std=gnu++17
build_unflags = -std=gnu++11
lib_ldf_mode = deep


[develop_ESP]
extends = custom, ESP32_develop
build_flags =
  ${custom.build_flags}
  ${ESP32_develop.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D OPENKNX_TIME_TESTCOMMAND
  -D NET_USE_NTP
  "-D OPENKNX_TRACE1=IPC.*"


[custom_release_ESP32]
extends = ESP32_releases, custom, custom_ESP32
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_releases.build_flags}
  ${custom.build_flags}
  ${custom_ESP32.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D NET_USE_NTP


; ------ REG1-LAN-TP-Base (develop) ------

[env:develop_REG1_LAN_TP_BASE]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_8MB, ESP32_UPLOAD_USB
build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D CONFIG_ETH_ENABLED
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial

[env:develop_REG1_LAN_TP_BASE_JTAG]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_8MB, UPLOAD_ESP_PROG
build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D CONFIG_ETH_ENABLED
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial


; ------ REG1-LAN-TP-Base (release) ------

[env:release_REG1_LAN_TP_BASE]
extends = custom_release_ESP32, ESP32_8MB
build_flags =
  ${custom_release_ESP32.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D CONFIG_ETH_ENABLED
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D BOARD_HAS_PSRAM

[env:release_REG1_LAN_TP_BASE_OTA]
extends = custom_release_ESP32, ESP32_8MB
upload_protocol = espota
upload_port = 192.168.1.144
build_flags =
  ${custom_release_ESP32.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D CONFIG_ETH_ENABLED
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D BOARD_HAS_PSRAM
