;
; global custom
;
[custom]
build_flags =
  -D SERIAL_DEBUG=Serial
  -I lib/OGM-HardwareConfig/include/
  -fexceptions
  -D OPENKNX_LEDFUNC_BASE_PROG_UNCONFIGUREDSUPPORT


[develop]
extends = RP2040_develop, custom
build_flags =
  ${RP2040_develop.build_flags}
  ${custom.build_flags}
  ;-D OPENKNX_HEARTBEAT
   -D OPENKNX_HEARTBEAT_PRIO
  ; -D OPENKNX_RTT
  ; -D BUFFER_SIZE_UP=10240
  ; -D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
  ; -D LOGIC_TRACE
  ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  ; "-D OPENKNX_TRACE1=Common.*"
  ; "-D OPENKNX_TRACE3=DummyChannel<1>"
  ; "-D OPENKNX_TRACE4=DummyChannel<[3-5]>"
  ;-D KNX_LOG_COUPLER
  ;-D KNX_LOG_IP
  ;-D KNX_LOG_TUNNELING
  -D KNX_IP_W5500
  -D OPENKNX_TIME_TESTCOMMAND
  -D OPENKNX_RUNTIME_STAT
  -D OPENKNX_RUNTIME_STAT_BUCKETN=10
  "-D OPENKNX_RUNTIME_STAT_BUCKETS=5000, 6000, 7000, 8000, 10000, 15000, 30000, 50000, 100000"


; this config block is for specifing options that are valid for all release builds
[releases]
extends = RP2040_releases, custom
build_flags =
  ${RP2040_releases.build_flags}
  ${custom.build_flags}
  -D KNX_IP_W5500


; ------ PiPico ------
[env:develop_PIPICO]
extends = develop, RP2040_2MB, RP2040_EXCHANGE_2MB
build_flags =
   ${develop.build_flags}
   ${RP2040_EXCHANGE_2MB.build_flags}
  -D BOARD_PIPICO
  -D KNX_IP_LAN

[env:develop_PIPICO_USB]
extends = RP2040_UPLOAD_USB, env:develop_PIPICO

[env:develop_PIPICO_JLINK]
extends = UPLOAD_JLINK, env:develop_PIPICO


; ------ REG1-Eth------
[env:develop_REG1_ETH]
extends = develop, RP2040_16MB, RP2040_EXCHANGE_16MB
# monitor_port = /dev/cu.usbmodem2101
build_flags =
   ${KNX_TP.build_flags}
   ${develop.build_flags}
   ${RP2040_EXCHANGE_16MB.build_flags}
   -I lib/OGM-HardwareConfig/include/
   -D DEVICE_REG1_ETH
   -D KNX_IP_LAN
   # -D KNX_IP_GENERIC
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400


[env:develop_REG1_ETH_USB]
extends = RP2040_UPLOAD_USB, env:develop_REG1_ETH

[env:develop_REG1_ETH_JLINK]
extends = UPLOAD_JLINK, env:develop_REG1_ETH

[env:beta_REG1_ETH_USB]
extends = RP2040_UPLOAD_USB, env:develop_REG1_ETH
build_flags =
   ${env:develop_REG1_ETH.build_flags}

; ------ W5500-EVB-Pico ------
[env:develop_W5500_EVB_PICO]
extends = develop, RP2040_2MB, RP2040_EXCHANGE_2MB
build_flags =
   ${KNX_TP.build_flags}
   ${develop.build_flags}
   ${RP2040_EXCHANGE_2MB.build_flags}
  -D BOARD_W5500_EVB_PICO
  -D KNX_IP_W5500

[env:develop_W5500_EVB_PICO_USB]
extends = RP2040_UPLOAD_USB, env:develop_W5500_EVB_PICO

[env:develop_W5500_EVB_PICO_JLINK]
extends = UPLOAD_JLINK, env:develop_W5500_EVB_PICO


; ------ PiPicoW ------
[env:develop_PIPICOW]
extends = develop, RP2040_2MB, RP2040_EXCHANGE_2MB
board = rpipicow
build_flags =
   ${KNX_TP.build_flags}
   ${develop.build_flags}
   ${RP2040_EXCHANGE_2MB.build_flags}
  -D BOARD_PIPICOW
  -D KNX_IP_WIFI

[env:develop_PIPICOW_USB]
extends = RP2040_UPLOAD_USB, env:develop_PIPICOW

[env:develop_PIPICOW_JLINK]
extends = UPLOAD_JLINK, env:develop_PIPICOW



;  Releases
[env:release_REG1_ETH]
extends = releases, RP2040_16MB, RP2040_EXCHANGE_16MB
build_flags =
   ${KNX_TP.build_flags}
   ${releases.build_flags}
   ${RP2040_EXCHANGE_16MB.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_ETH
  -D KNX_IP_LAN
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400

; ESP32
[develop_ESP]
extends = custom, ESP32_develop
build_flags =
  ${custom.build_flags}
  ${ESP32_develop.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_USB_EXCHANGE_IGNORE
  ;-D OPENKNX_FILE_TRANSFER_IGNORE
  -D OPENKNX_TIME_TESTCOMMAND
  -D NET_USE_NTP
  ; ; -D OPENKNX_HEARTBEAT_PRIO
  ; -D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
  ; -D LOGIC_TRACE
  ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  "-D OPENKNX_TRACE1=IW.*"
  ;"-D OPENKNX_TRACE2=Logic.*"
  ;"-D OPENKNX_TRACE3=*.*"
  ; -D OPENKNX_RTT
  ; -D BUFFER_SIZE_UP=10240





[custom_ESP32]
extends = ESP32, custom
build_flags =
  #-D OPENKNX_RUNTIME_STAT
  ${BASE.build_flags}
  -D OPENKNX_DUALCORE
  -D USE_ESP_ASNC_WEB_SERVER
   # -D OPENKNX_WATCHDOG

  -std=gnu++17
 # build_flags = -std=gnu++17
  #-D AC_USE_LITTLEFS
  #-D PB_USE_LITTLEFS
  # -D USE_AUTO_CONNECT
  
build_unflags = -std=gnu++11
lib_ldf_mode = deep # deep+ and chain+ prevent finding WiFi.h for ESP32 builds
lib_deps = 
#  ESP Async WebServer


[custom_release_ESP32]
extends = ESP32_releases, custom, custom_ESP32
build_flags =
   ${KNX_TP.build_flags}
  ${ESP32_releases.build_flags}
  ${custom.build_flags}
  ${custom_ESP32.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D NET_USE_NTP

; ------ REG1 ESP ------

[env:develop_REG1_ESP_DEV_IP_WLAN]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_UPLOAD_USB, ESP32_8MB
;platform = espressif32 @ ^6.7.0 ; IDF 4.4
build_flags =
  ${KNX_IP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  -D KNX_IP_WIFI
  -D SERIAL_DEBUG=Serial


[env:develop_REG1_ESP_DEV_IP_NET]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_UPLOAD_USB, ESP32_8MB
;platform = espressif32 @ ^6.7.0 ; IDF 4.4
build_flags =
  ${KNX_IP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
  -D CONFIG_ETH_ENABLED
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial
  -UKNX_IP_WIFI
  -UKNX_NETIF

; ------ REG1 ESP ------
[env:develop_REG1_ESP_DEV_TP_NET]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_UPLOAD_USB, ESP32_8MB
;platform = espressif32 @ ^6.7.0 ; IDF 4.4
build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
  -D CONFIG_ETH_ENABLED
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial
  -UKNX_IP_WIFI
  -UKNX_NETIF

[env:develop_REG1_ESP_DEV_TP_NET_JTAG]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_UPLOAD_USB, ESP32_8MB, UPLOAD_ESP_PROG
;platform = espressif32 @ ^6.7.0 ; IDF 4.4

build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_DEV_REG1_LAN_TP_Base_V00_11
  -D CONFIG_ETH_ENABLED
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial
  -UKNX_IP_WIFI
  -UKNX_NETIF
; ; Debug
; debug_tool = esp-prog
; debug_init_break = tbreak setup
; ; Set optimization level and amount of debug information generated by the compiler
; debug_build_flags = -O0 -ggdb3 -g3
; upload_protocol = esp-prog
; upload_speed = 921600


; ------ REG1-LAN-TP-Base ------
[env:develop_REG1_LAN_TP_BASE]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_8MB, ESP32_UPLOAD_USB
;platform = espressif32 @ ^6.7.0 ; IDF 4.4
build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D CONFIG_ETH_ENABLED
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial

[env:develop_REG1_LAN_TP_BASE_JTAG]
extends = custom_ESP32, ESP32_libs, develop_ESP, ESP32_8MB, UPLOAD_ESP_PROG
;platform = espressif32 @ ^6.7.0 ; IDF 4.4
build_flags =
  ${KNX_TP.build_flags}
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D CONFIG_ETH_ENABLED
  -D KNX_IP_LAN
  -D SERIAL_DEBUG=Serial

; ------ Adafruit ESP32 Feather V2 ------
[board_Adafruit_Feather_ESP32_V2]
extends = ESP32_8MB
build_flags =
  -D DEVICE_ADAFRUIT_ESP32_FEATHER_V2
 # -D OPENKNX_FCB_DEBUG
 -D KNX_IP_WIFI
#  -UBOARD_HAS_PSRAM
board = adafruit_feather_esp32_v2

[env:develop_Adafruit_Feather_ESP32_V2]
extends = custom_ESP32, ESP32_libs, develop_ESP, board_Adafruit_Feather_ESP32_V2
build_flags =
  ${custom_ESP32.build_flags}
  ${develop_ESP.build_flags}
  ${board_Adafruit_Feather_ESP32_V2.build_flags}
lib_deps = 
  ${custom_ESP32.lib_deps}

[env:develop_Adafruit_Feather_ESP32_V2_USB]
extends = env:develop_Adafruit_Feather_ESP32_V2, ESP32_UPLOAD_USB
build_flags =
  ${KNX_TP.build_flags}
  ${env:develop_Adafruit_Feather_ESP32_V2.build_flags}


[env:develop_Adafruit_Feather_ESP32_V2_USB_IP]
extends = env:develop_Adafruit_Feather_ESP32_V2, ESP32_UPLOAD_USB
build_flags =
  ${KNX_IP.build_flags}
  ${env:develop_Adafruit_Feather_ESP32_V2.build_flags}
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  -D KNX_IP_WIFI

[env:develop_Adafruit_Feather_ESP32_V2_OTA]
extends = env:develop_Adafruit_Feather_ESP32_V2, ESP32_UPLOAD_USB
upload_protocol = espota
upload_port = OpenKNX-FeatherV2-TestBoard #  # IP Address or Hostname



; Release

[env:release_REG1_LAN_TP_BASE]
extends = custom_release_ESP32, ESP32_8MB
build_flags =
   ${custom_release_ESP32.build_flags}  
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D CONFIG_ETH_ENABLED  
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D BOARD_HAS_PSRAM
 
[env:release_REG1_LAN_TP_BASE_OTA]
extends = custom_release_ESP32, ESP32_8MB
upload_protocol = espota
upload_port = 192.168.0.59 # IP Address
build_flags =
   ${custom_release_ESP32.build_flags}  
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_TP_BASE
  -D CONFIG_ETH_ENABLED 
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN 
  -D BOARD_HAS_PSRAM


[env:release_REG1_LAN_BASE]
extends = custom_release_ESP32, ESP32_8MB
build_flags =
  ${custom_release_ESP32.build_flags}  
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_REG1_LAN_BASE
  -D OPENKNX_INFOLED1_DEFAULT=0
  -D OPENKNX_INFOLED2_DEFAULT=10
  -D OPENKNX_INFOLED3_DEFAULT=400
  -D KNX_IP_LAN
  -D CONFIG_ETH_ENABLED  
  -D BOARD_HAS_PSRAM
  ${KNX_IP.build_flags}
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0

[env:release_Adafruit_Feather_ESP32_V2_TP]
extends = custom_release_ESP32, ESP32_8MB, board_Adafruit_Feather_ESP32_V2
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_Adafruit_Feather_ESP32_V2.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_ADAFRUIT_ESP32_FEATHER_V2
  -D KNX_IP_WIFI

[env:rel_Adafruit_Feather_ESP32_V2_TP_OTA]
extends = custom_release_ESP32, ESP32_8MB, board_Adafruit_Feather_ESP32_V2
upload_protocol = espota
upload_port = #192.168.0.?? # IP Address
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_Adafruit_Feather_ESP32_V2.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_ADAFRUIT_ESP32_FEATHER_V2
  -D KNX_IP_WIFI


[env:release_Adafruit_Feather_ESP32_V2_IP]
extends = custom_release_ESP32, ESP32_8MB, board_Adafruit_Feather_ESP32_V2
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_Adafruit_Feather_ESP32_V2.build_flags}
  -I lib/OGM-HardwareConfig/include/
  -D DEVICE_ADAFRUIT_ESP32_FEATHER_V2
  -D KNX_IP_WIFI
  ${KNX_IP.build_flags}
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0